name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t cloudcredits-webapp .
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ SheikhSahil }}
        password: ${{ ZXCVBNM_1a1 }}
    - name: Push to Docker Hub
      run: docker push cloudcredits-webapp

# dckr_pat_jhWVoS2MM6jsr5DAJOf0zUPsz70